services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant_app
    command: 'php artisan serve --host=0.0.0.0'
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: restaurant_db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
